#!/bin/bash

JDK6=/usr/lib/jvm/java-6-oracle/
JDK7=/usr/lib/jvm/java-7-oracle/
JDK8=/usr/lib/jvm/java-8-oracle/
JDK11=/usr/lib/jvm/java-11-oracle/

case "$1" in
        "6")
                export JAVA_HOME=$JDK6
                export ANT_OPTS="-Xms256m -Xmx4g -XX:PermSize=512m -XX:MaxPermSize=4g"
                ;;
        "7")
                export JAVA_HOME=$JDK7
                export ANT_OPTS="-Xms256m -Xmx4g -XX:PermSize=512m -XX:MaxPermSize=4g"
                ;;
        "8")
                export JAVA_HOME=$JDK8
                export ANT_OPTS="-Xms256m -Xmx4g"
                ;;
        "11")
                export JAVA_HOME=$JDK11
                export ANT_OPTS="-Xms256m -Xmx4g"
                ;;
        *)
                echo "Unknown JDK version! Specify 6, 7, 8, or 11!"
                ;;
esac
export JDK_HOME=$JAVA_HOME

echo JAVA_HOME set to $JAVA_HOME
export PATH=$JAVA_HOME/bin:$PATH
java -version